<?php

$jobs = View::paginate($this->jobs);
$resolveJobStatus = function ($job) {
	if ($job->expiresAt() || $job->delayUntil()) {
		return 'd';
	}
	elseif ($job->lockId() == -1) {
		return 'f';
	}
	elseif ($job->lockId()) {
		return 'r';
	}
	return 'p';
};


$worker = $this->worker;
?>

<div class="container">
	<ol class="breadcrumb">
		<li><a href="<?= View::urlFor('site') ?>"><i class="fa fa-home"></i></a></li>
		<li>Jobs</li>
	</ol>
	<div class="row">
		<div class="col-xs-12">
			<?php if (empty($worker['running'])): ?>
				<div class="alert alert-danger clearfix">
					Queue Worker is not running
					<a href="" class="btn btn-xs btn-primary pull-right">Restart</a>
				</div>
			<?php else: ?>
				<div class="alert alert-info">Queue Worker is running (PID: <?=$worker['pid']?>)</div>
			<?php endif; ?>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<a class="btn btn-xs btn-info" href="<?= View::urlFor('dashboard') ?>">Refresh</a>
			<a class="btn btn-xs btn-info" href="<?= View::urlFor('email-failure') ?>">Send Email (failure)</a>
			<a class="btn btn-xs btn-info" href="<?= View::urlFor('email-success') ?>">Send Email (success)</a>
			<a class="btn btn-xs btn-info" href="<?= View::urlFor('process-image') ?>">Process an Image</a>
<!--			<a class="btn btn-xs btn-info" href="--><?//= View::urlFor('pop-a-top') ?><!--">Pop a top</a>-->
<!--			<a class="btn btn-xs btn-info" href="--><?//= View::urlFor('in-the-future') ?><!--">In the future</a>-->
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<div class="panel">
				<div class="panel-body">
					<table class="table">
						<thead>
						<tr>
							<th>Queue</th>
							<th>Status</th>
							<th>Job</th>
							<th>Payload</th>
							<th><span class="sr-only">Actions</span></th>
						</tr>
						</thead>
						<tbody>
						<?php
						if (empty($this->jobs)) {
							echo "<tr><td colspan='5' style='text-align:center'>Waiting</td></tr>";
						}

						foreach ($this->jobs->items() as $job):
						$status = $resolveJobStatus($job);
						?>
							<tr>
								<td><?= $job->queue() ?></td>
								<td><?= View::jobStatus($job) ?></td>
								<td><?= $job->name() ?></td>
								<td><?= json_encode($job->payload()) ?></td>
								<td><?php switch($status) {
										case 'f':
											echo $this->partial('views/_partials/queue/actions/failed', ['job' => $job]);
											break;
										case 'p':
											echo $this->partial('views/_partials/queue/actions/pending', ['job' => $job]);
											break;
										case 'r':
											echo $this->partial('views/_partials/queue/actions/running', ['job' => $job]);
											break;
										case 'd':
											echo $this->partial('views/_partials/queue/actions/delayed', ['job' => $job]);
											break;
									}?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>