---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ../vagrant.yml
  vars:
    percona_server_root_password: root
    php_version: 7.1
    php_fpm_listen: "127.0.0.1:9000"
    php_fpm_daemon: "php{{ php_version }}-fpm"
    php_fpm_conf_path: "/etc/php/{{ php_version }}/fpm"
    php_conf_paths:
      - "/etc/php/{{ php_version }}/fpm"
      - "/etc/php/{{ php_version }}/cli"
    php_extension_conf_paths:
      - "/etc/php/{{ php_version }}/fpm/conf.d"
      - "/etc/php/{{ php_version }}/cli/conf.d"
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_packages:
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-bz2"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-readline"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-xmlrpc"
      - php-apcu
      - php-xdebug
      - composer
    nginx_worker_connections: 1024
  roles:
    - dincho.percona-server
    - benjamin-smith.ondrej-php-repo
    - geerlingguy.nginx
    - geerlingguy.php
#  tasks:
#    - become_user: vagrant
#      composer:
#        command: install
#        working_dir: /vagrant
#        no_dev: false
#        ignore_platform_reqs: true
#        prefer_dist: true

