<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
<!--	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" rel="stylesheet" crossorigin="anonymous">-->
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">
	<link rel="stylesheet" href="/assets/default/css/theme.css">
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<script type="text/javascript">
		var pageFunctions = [];
	</script>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
					aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?= $this->baseUrl ?>">Brooks Institute</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav pull-right ">
				<li><p class="navbar-text"></p></li>
				<li><a href="<?= $this->baseUrl ?>/logout">Logout</a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="container application">
	<div class="row no-gutters">
		<div class="col-md-3" id="navbar-side">
			<nav class="nav-side-menu">
				<h4>Application Sections</h4>
				<!-- Page Nav -->
				<div aria-label="application pages" role="navigation">
					<ul>
						<li class="<?= $this->stage === 'contact' ? 'active':'' ?>" id="ufe-nav-p-1"><a href="/application/contact">Contact Information</a></li>
						<li class="<?= $this->stage === 'personal' ? 'active':'' ?>" id="ufe-nav-p-2"><a href="/application/personal">Personal Information</a></li>
						<li class="<?= $this->stage === 'other' ? 'active':'' ?>" id="ufe-nav-p-3"><a href="/application/other">Other Information</a></li>
						<li class="<?= $this->stage === 'academic-history' ? 'active':'' ?>" id="ufe-nav-p-7"><a href="/application/academic-history">Academic History</a></li>
						<li class="<?= $this->stage === 'optional' ? 'active':'' ?>" id="ufe-nav-p-9"><a href="/application/optional">Optional Information</a></li>
						<li class="<?= $this->stage === 'signature' ? 'active':'' ?>" id="ufe-nav-p-10"><a href="/application/signature">Signature</a></li>
					</ul>
				</div>
				<div class="alert alert-muted">
					Locked pages (<span class="glyphicon glyphicon-lock"></span>) will open as requirements are met in the form.
				</div>
			</nav>
		</div>
		<div class="col-md-9" id="app-content">
			<div class="container-fluid">
				<header class="page-header">
					<h3>Admissions Application</h3>
					<div class="applicant mutedText clearfix">
						<span class="pull-left">Non-refundable application fee: $50.00</span>
						<strong class="pull-right"><?= $this->user->lastName() . ', ' . $this->user->firstName() ?></strong>
					</div>
				</header>
				<?=$this->buffer?>
				<footer class="page-footer">
					<div class="page-paginator">
						Page 1 of 20
					</div>
					<div class="row no-gutters page-navigation">
						<div class="col-xs-3">
							<button class="btn">&lt; Previous Page</button>
						</div>
						<div class="col-xs-6">
							<button class="btn">Save</button>
							<button class="btn">Save &amp; Exit</button>
						</div>
						<div class="col-xs-3">
							<button class="btn btn-next pull-right">Next Page &gt;</button>
						</div>
					</div>
				</footer>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		for (cls in pageFunctions) {
			pageFunctions[cls]();
		}

		$('input[type=checkbox][data-toggle^=yesno-toggle]').bootstrapToggle({
			on: 'Yes',
			off: 'No',
			size: 'small',
			onstyle: 'toggle-yes',
																			 })
	});
	//function to fix height of iframe!
	var calcHeight = function() {
		var headerDimensions = $('.preview__header').height();
		$('.full-screen-preview__frame').height($(window).height() - headerDimensions);
	}

	$(document).ready(function() {
		calcHeight();
	});

	$(window).resize(function() {
		calcHeight();
	}).load(function() {
		calcHeight();
	});
</script>
</body>
</html>

