<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<!--	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" rel="stylesheet" crossorigin="anonymous">-->
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css">
	<link rel="stylesheet" href="/assets/default/css/theme.css">
 	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<script type="text/javascript">
		var pageFunctions = [];
	</script>
</head>
<body>

<?=$this->buffer?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
		for (cls in pageFunctions) {
			pageFunctions[cls]();
		}
	});
	//function to fix height of iframe!
	var calcHeight = function() {
		var headerDimensions = $('.preview__header').height();
		$('.full-screen-preview__frame').height($(window).height() - headerDimensions);
	}

	$(document).ready(function() {
		calcHeight();
	});

	$(window).resize(function() {
		calcHeight();
	}).load(function() {
		calcHeight();
	});
</script>
</body>
</html>

